services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-network
    
  backend:
    build: ./server
    container_name: backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/myDatabase
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mongo
    networks:
      - app-network
  
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    